### ISSUE TITLE
Menambahkan contoh untuk hasil dari tema

### ISSUE THREAD

**Issue by muhammadfarras** [muhammadfarras/practice-git#6]
Assalamualaikum @muhammadfarras ada bebera yang harus ditambahkan

1. Tambahkan contoh kode
2. Tabel 

<table>
<tr><td>Seperti ini</td><td>Contoh tabel nya</td></tr>
</table>

`var myName : String ="Muhammad Farras Ma'ruf `

**Comment by BrownTofu** [comment]
OK im trying to add those features

**Comment by muhammadfarras** [comment]
Oke then
